/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgemini.addressbooktest;

import org.junit.Test;

import com.capgemini.addressbook.Executer;

import static org.junit.Assert.*;

public class LibraryTest {
}
